#!/usr/bin/env node
// Bloom's stochastic controls, as a layer × parameter matrix.
//
//   npm run stoch      → rewrite docs/bloom-stochastic-controls.md
//
// EVERYTHING comes from the app: MEMBERSHIP from `_AMB_LAYER_SCHEMA`, and TYPE /
// GRAIN / description from `_AMB_STOCH` (js/bloops/17-ambient.js), which is the
// same table the card readouts render from. So the doc cannot drift from the UI,
// and a control that is in a Variance/Performance group but missing from
// _AMB_STOCH fails HERE, by name, instead of quietly going undescribed in both.
//
// Needs the dev server (`npm start`).
import fs from 'fs';
import path from 'path';

const TYPE_NAME = { rhy: 'Rhythm', pit: 'Pitch', dyn: 'Dynamics', art: 'Articulation', len: 'Length' };
const GRAINS = [
  ['note',  'one NOTE',  'a fresh choice for every note played'],
  ['slot',  'one SLOT',  'a choice per candidate onset, played or not'],
  ['cycle', 'one CYCLE', 'one choice for the whole phrase / pass'],
];
const ROOT = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..');
const URLBASE = process.env.BLOOPS_URL || 'http://localhost:3001/bloops.html';

const puppeteer = (await import(path.join(ROOT, 'node_modules/puppeteer-core/lib/puppeteer/puppeteer-core.js'))).default;
const CHROME = process.env.CHROME_PATH || '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';
const browser = await puppeteer.launch({ executablePath: CHROME, headless: 'new', args: ['--no-sandbox'] });
const page = await browser.newPage();
try {
  await page.goto(URLBASE, { waitUntil: 'networkidle2', timeout: 45000 });
} catch (e) {
  console.error('Could not reach ' + URLBASE + ' — is `npm start` running?');
  await browser.close(); process.exit(2);
}
await new Promise(r => setTimeout(r, 2500));
const data = await page.evaluate(() => {
  const S = _AMB_LAYER_SCHEMA, types = Object.keys(S), cells = {}, labels = {};
  types.forEach(t => { let g = '';
    (S[t].ctrls || []).forEach(c => {
      if (!Array.isArray(c)) return;
      if (c[0] === 'grp') { g = c[1]; return; }
      if (g !== 'Variance' && g !== 'Performance') return;
      const k = c[1]; if (!k) return;
      cells[k] = cells[k] || {}; cells[k][t] = 1;
      labels[k] = labels[k] || new Set(); labels[k].add(c[2] || k);
    }); });
  // _AMB_STOCH holds functions (the value-aware `at`); ship only what serialises.
  const meta = {};
  Object.keys(_AMB_STOCH).forEach(k => {
    const m = _AMB_STOCH[k];
    meta[k] = { type: m.type, grain: m.grain, draws: m.draws || '', does: m.does || '', off: m.off || '' };
  });
  return { types: types.map(t => ({ key: t, label: S[t].label || t })), cells, meta,
    labels: Object.fromEntries(Object.entries(labels).map(([k, v]) => [k, [...v]])) };
});
await browser.close();

const META = data.meta;
const keys = Object.keys(data.cells);
const unknown = keys.filter(k => !META[k]);
if (unknown.length) {
  console.error('Control(s) in a Variance/Performance group but missing from _AMB_STOCH: ' + unknown.join(', ') +
    '\nAdd each to _AMB_STOCH in js/bloops/17-ambient.js with its type, grain, does and off — ' +
    'read type and grain from the control’s draw site in the emitter, not from its label.\n' +
    'Until you do, the card shows no description for it and this doc cannot list it.');
  process.exit(1);
}
const stale = Object.keys(META).filter(k => !data.cells[k]);
const cnt = k => Object.keys(data.cells[k]).length;
const tname = k => TYPE_NAME[META[k].type] || META[k].type;
const cols = keys.sort((a, b) =>
  GRAINS.findIndex(g => g[0] === META[a].grain) - GRAINS.findIndex(g => g[0] === META[b].grain)
  || cnt(b) - cnt(a) || a.localeCompare(b));
const lab = k => data.labels[k].join(' / ');
const rowTotal = t => cols.filter(k => data.cells[k][t.key]).length;
const byType = {}; cols.forEach(k => { (byType[tname(k)] = byType[tname(k)] || []).push(k); });

let md = `# Bloom — stochastic controls by layer

> Generated by \`npm run stoch\`. Every column comes from the running app —
> membership from \`_AMB_LAYER_SCHEMA\`, type/grain/wording from \`_AMB_STOCH\`
> (\`js/bloops/17-ambient.js\`), which is also what the card readouts render from.
> Do not hand-edit; edit \`_AMB_STOCH\` and re-run.
> Visual version: https://claude.ai/code/artifact/5283fea5-96be-46ca-a878-44c845451f28

Every control in each layer's **Variance** and **Performance** groups — ${cols.length} controls
across ${data.types.length} layer types. Two axes:

- **Type** — what the control edits.
- **Grain** — what counts as ONE set of choices. This is the axis that matters:
  only the \`cycle\` controls are what Write / Evolve actually captures, so a
  "play something new every N passes" setting governs those and nothing else.

Neither is derivable from a label — both come from each control's **draw site**
in the emitters. That is why they are recorded in the app rather than here.

## By grain

`;
GRAINS.forEach(([u, title, desc]) => {
  const ks = cols.filter(k => META[k].grain === u);
  md += `### ${title} — ${desc}\n\n`;
  md += `| control | key | type | layers | what a user sees | what it draws |\n|---|---|---|---|---|---|\n`;
  ks.forEach(k => { md += `| ${lab(k)} | \`${k}\` | ${tname(k)} | ${cnt(k)} | ${META[k].does} | ${META[k].draws} |\n`; });
  md += `\n`;
});
md += `## By type

| type | controls | count |
|---|---|---|
`;
Object.keys(byType).sort((a, b) => byType[b].length - byType[a].length).forEach(t => {
  md += `| ${t} | ${byType[t].map(k => lab(k)).join(' · ')} | ${byType[t].length} |\n`;
});
md += `\n## By layer\n\n| layer | controls | count |\n|---|---|---|\n`;
data.types.forEach(t => {
  md += `| ${t.label} | ${cols.filter(k => data.cells[k][t.key]).map(k => lab(k)).join(' · ') || '—'} | ${rowTotal(t)} |\n`;
});
const nNote = cols.filter(k => META[k].grain === 'note').length;
const nCycle = cols.filter(k => META[k].grain === 'cycle').length;
const nRhyPit = (byType.Rhythm || []).length + (byType.Pitch || []).length;
md += `
## What the shape says

- **${nNote} of ${cols.length}** controls re-decide on every note, so no amount of freezing
  makes them repeat. Only the **${nCycle} cycle** controls are what Write / Evolve captures.
- **Rhythm and Pitch are ${nRhyPit} of ${cols.length}.** Loudness, articulation and length are
  ${cols.length - nRhyPit} controls between them.
- \`humanize\` is the only control on unseeded \`Math.random\` — which is exactly why
  the same take replays identically except for its humanize.
- **${cols.filter(k => cnt(k) === 1).length}** controls belong to a single layer. That tail is per-layer character,
  not duplication, and collapsing it would flatten what makes a Motif a Motif.

## Resolved

- \`phrasing\` (Motif "Phrasing" / Riff "Articulate") drew **zero** RNG at any setting —
  a deterministic blend of the seed pattern's shape. Moved out of Variance into
  Timing, so every control listed here genuinely draws.
- \`startVary\` (Bed) and \`phraseVary\` (Motif) were the same algorithm written twice.
  Still two fields, now one implementation: \`_ambStartOffset\`.
- Type and grain used to live in this generator, where the UI could not reach them.
  They now live in \`_AMB_STOCH\` and feed both the doc and the card readouts.

## Open

- \`pitchVar\` (Bass "Walk", per **slot**) and \`pitchVary\` (Arp/Drone, per **cycle**)
  differ by one letter *and* by grain — a live trap when reading this code.
- Rests and Ghosts are one bipolar density axis pointing opposite ways. Merging is
  a real behaviour change: it hands ghosts to five layers that never had them.
- Six of Motif's controls (Contour, Gravity, Stutter, Twist, Ornament, Slide) are
  one idea — how the walk behaves — presented as six sliders.
- The readout is gated to one layer type (\`_AMB_STOCH_UI\`) while the wording is
  reviewed. Widen it, then delete the gate.
`;
if (stale.length) md += `\n> **Note:** \`${stale.join('`, `')}\` ${stale.length === 1 ? 'is' : 'are'} in \`_AMB_STOCH\` but no longer in any Variance/Performance group.\n`;

const out = path.join(ROOT, 'docs/bloom-stochastic-controls.md');
fs.writeFileSync(out, md);
console.log('wrote ' + path.relative(ROOT, out) + ' — ' + cols.length + ' controls, ' +
  data.types.length + ' layers, ' + Object.keys(byType).length + ' types' +
  (stale.length ? ' (stale: ' + stale.join(',') + ')' : ''));
